{{- if .Values.todo.autoscaling.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.todo.name }}-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.todo.name }}
  minReplicas: {{ .Values.todo.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.todo.autoscaling.maxReplicas }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 120
      policies:
      - type: Percent
        value: {{ .Values.todo.autoscaling.scaleDownCPUUtilizationPercentage }}
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: {{ .Values.todo.autoscaling.scaleUpCPUUtilizationPercentage }}
        periodSeconds: 30
      - type: Pods
        value: 4
        periodSeconds: 15
      selectPolicy: Max
{{- end }}
