# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Terraform dependencies
  - package-ecosystem: "terraform"
    directory: "/aks-cluster"
    schedule:
      interval: "weekly"

  # Helm Chart dependencies
  - package-ecosystem: "helm"
    directory: "/helm"
    schedule:
      interval: "weekly"

  # MongoDB dependencies (assuming it's using a Node.js driver or similar)
  - package-ecosystem: "npm"
    directory: "/mongodb"
    schedule:
      interval: "weekly"

  # Node.js project dependencies
  - package-ecosystem: "npm"
    directory: "/node-todo"
    schedule:
      interval: "weekly"
