apiVersion: v2
name: mongodb
description: A Helm chart to install the mongodb to support the todo app
type: application
version: 0.1.0
appVersion: 1.16.0
home: https://github.com/dglynn/depoy-to-aks/treee/master/helm
maintainers:
  - name: dglynn
    url: https://github.com/dglynn
