apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.name }}
spec:
  type: {{ .Values.mongodb.service.type }}
  selector:
    app: {{ .Values.mongodb.name }}
  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: {{ .Values.mongodb.container.port }}
